[package]
name = "space-partitioning"
description = "Space partitioning data structures"
version = "0.1.0"
edition = "2018"
keywords = ["space-partitioning", "trees"]
categories = ["computer-vision", "graphics", "game-development"]
authors = ["Markus Mayer <widemeadows@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/sunsided/space-partitioning"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "interval_tree"
path = "examples/interval_tree.rs"

[dependencies]
num-traits = "0.2.14"
