[package]
name = "space-partitioning"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "interval_tree"
path = "examples/interval_tree.rs"

[dependencies]
